// <auto-generated />
using System;
using KisanApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KisaanApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260519130844_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KisanApi.Models.Fasal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AcreUsed")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("HarvestDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("KisanId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SowingDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KisanId");

                    b.ToTable("Fasals");
                });

            modelBuilder.Entity("KisanApi.Models.Kisan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("FreeZameen")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LeaseAmountPerAcre")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LeaseZameen")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OwnZameen")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalLeaseAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalZameen")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Kisans");
                });

            modelBuilder.Entity("KisanApi.Models.Ozar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KisanId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KisanId");

                    b.ToTable("Ozars");
                });

            modelBuilder.Entity("KisanApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KisanApi.Models.Zameen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsLease")
                        .HasColumnType("bit");

                    b.Property<int>("KisanId")
                        .HasColumnType("int");

                    b.Property<decimal>("LeaseAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LeaseAmountPerAcre")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAcre")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("KisanId");

                    b.ToTable("Zameens");
                });

            modelBuilder.Entity("KisanApi.Models.Fasal", b =>
                {
                    b.HasOne("KisanApi.Models.Kisan", "Kisan")
                        .WithMany("Fasals")
                        .HasForeignKey("KisanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kisan");
                });

            modelBuilder.Entity("KisanApi.Models.Ozar", b =>
                {
                    b.HasOne("KisanApi.Models.Kisan", "Kisan")
                        .WithMany("Ozars")
                        .HasForeignKey("KisanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kisan");
                });

            modelBuilder.Entity("KisanApi.Models.Zameen", b =>
                {
                    b.HasOne("KisanApi.Models.Kisan", "Kisan")
                        .WithMany("Zameens")
                        .HasForeignKey("KisanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kisan");
                });

            modelBuilder.Entity("KisanApi.Models.Kisan", b =>
                {
                    b.Navigation("Fasals");

                    b.Navigation("Ozars");

                    b.Navigation("Zameens");
                });
#pragma warning restore 612, 618
        }
    }
}
